# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'iOS Library Trials' do

# Functionalities
pod 'BraintreeDropIn'

# User Interface
pod 'SVProgressHUD'

end
