# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'iOS Library Trials' do

# Functionalities
pod 'Fabric'
pod 'Crashlytics'
pod 'BraintreeDropIn'
pod 'ZXingObjC', '~> 3.0'
pod 'AFNetworking'

# User Interface
pod 'SVProgressHUD'
pod 'MBProgressHUD', '~> 1.0.0'

end
